export const CANONICAL_BINDING_1_STYLES = [
  "Case Bound",
  "Case with Round Spine",
  "Double Pasted (3 Layers)",
  "Envelope",
  "File Folder",
  "Flapover",
  "Full Bound",
  "Full Bound Double Pasted",
  "Full Bound Stiff Cover",
  "NA",
  "Perfect Bound",
  "Portfolio",
  "Refer To Special Binding",
  "Soft Cover",
  "Split Case",
  "Stiff Cover",
  "Unbound",
] as const;
