import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { UserProfileInfo, TeamMemberItem } from "../types";
import { fetchUsersApi } from "../api";
import { fetchProductDetailsApi, fetchSampleRequestsApi, ProductDetailItem } from "@/features/sample-requests/api";
import { SampleRequestItem } from "@/features/sample-requests/types";
import { ProductSpecificationsDrawer } from "@/features/sample-requests/components/ProductSpecificationsDrawer";
import { PlantManagementModal } from "@/features/sample-requests/components/PlantManagementModal";
import { AlertCircle, ArrowRight, BarChart3, Building2, CheckCircle2, ChevronRight, Clock, Factory, FileText, Layers, Plus, RefreshCw, Search, Settings, Users, Workflow } from "@/components/ui/icons";

type WorkflowId = "marketing" | "creative" | "studio" | "operations";
type QueueView = "all" | "attention" | "completed";
interface WorkflowLane { id: WorkflowId; label: string; description: string; color: string; soft: string; }

const WORKFLOW_LANES: WorkflowLane[] = [
  { id: "marketing", label: "Marketing intake", description: "Briefs and request qualification", color: "#2563eb", soft: "#eff6ff" },
  { id: "creative", label: "Creative design", description: "Artwork and customer proofs", color: "#db2777", soft: "#fdf2f8" },
  { id: "studio", label: "Studio & CAD", description: "Structure and pre-press readiness", color: "#7c3aed", soft: "#f5f3ff" },
  { id: "operations", label: "SAMP & operations", description: "Feasibility, plant and closure", color: "#d97706", soft: "#fffbeb" },
];

function statusOf(request: SampleRequestItem) { return (request.status || "").toLowerCase(); }
function isCompleted(request: SampleRequestItem) { const status = statusOf(request); return status.includes("dispatch") || status.includes("closed") || status.includes("deal") || status.includes("approved"); }
function isOverdue(request: SampleRequestItem) { if (!request.sampleRequiredDate || isCompleted(request)) return false; const target = new Date(`${request.sampleRequiredDate}T23:59:59`); return !Number.isNaN(target.getTime()) && target.getTime() < Date.now(); }
function isDueSoon(request: SampleRequestItem) { if (!request.sampleRequiredDate || isCompleted(request) || isOverdue(request)) return false; const target = new Date(`${request.sampleRequiredDate}T23:59:59`).getTime(); return target - Date.now() <= 7 * 24 * 60 * 60 * 1000; }
function laneFor(request: SampleRequestItem): WorkflowId { const status = statusOf(request); if (status.includes("creative")) return "creative"; if (status.includes("studio")) return "studio"; if (status.includes("samp") || status.includes("plant") || status.includes("execution") || status.includes("qc")) return "operations"; return "marketing"; }
function isCostingRequest(request: SampleRequestItem) { return Boolean(request.qtyDesignCosting || request.requestTypes?.includes("costing") || statusOf(request).includes("cost")); }
function formatDate(value?: string | null) { if (!value) return "—"; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-IN", { day: "2-digit", month: "short" }); }
function initials(name: string) { return name.split(" ").map((part) => part[0]).join("").toUpperCase().slice(0, 2); }
function statusTone(request: SampleRequestItem) { const status = statusOf(request); if (isCompleted(request)) return { label: "Complete", className: "erp-status-success" }; if (isOverdue(request)) return { label: "Overdue", className: "erp-status-danger" }; if (status.includes("creative")) return { label: "Creative", className: "erp-status-pink" }; if (status.includes("studio")) return { label: "Studio", className: "erp-status-violet" }; if (status.includes("plant") || status.includes("execution")) return { label: "Operations", className: "erp-status-warning" }; return { label: "Intake", className: "erp-status-info" }; }

export interface DashboardOverviewProps { user?: UserProfileInfo | null; }

export const DashboardOverview: React.FC<DashboardOverviewProps> = ({ user }) => {
  const navigate = useNavigate();
  const [requests, setRequests] = useState<SampleRequestItem[]>([]);
  const [users, setUsers] = useState<TeamMemberItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [queueView, setQueueView] = useState<QueueView>("attention");
  const [search, setSearch] = useState("");
  const [isPlantModalOpen, setIsPlantModalOpen] = useState(false);
  const [selectedRequest, setSelectedRequest] = useState<SampleRequestItem | null>(null);
  const [specDetails, setSpecDetails] = useState<ProductDetailItem[]>([]);
  const [isLoadingSpecs, setIsLoadingSpecs] = useState(false);

  const loadDashboardData = useCallback(async (refresh = false) => {
    if (refresh) setIsRefreshing(true); else setIsLoading(true);
    try { const [requestData, memberData] = await Promise.all([fetchSampleRequestsApi(), fetchUsersApi()]); setRequests(requestData || []); setUsers(memberData || []); }
    catch (error) { console.error("Failed to load dashboard data:", error); }
    finally { setIsLoading(false); setIsRefreshing(false); }
  }, []);
  useEffect(() => { loadDashboardData(); }, [loadDashboardData]);

  const metrics = useMemo(() => { const completed = requests.filter(isCompleted).length; const overdue = requests.filter(isOverdue).length; const dueSoon = requests.filter(isDueSoon).length; return { total: requests.length, open: requests.length - completed, completed, overdue, dueSoon, costing: requests.filter(isCostingRequest).length, customers: new Set(requests.map((request) => request.customer?.trim()).filter(Boolean)).size, plants: new Set(requests.map((request) => request.targetPlant?.trim()).filter(Boolean)).size, completionRate: requests.length ? Math.round((completed / requests.length) * 100) : 0 }; }, [requests]);
  const laneStats = useMemo(() => WORKFLOW_LANES.map((lane) => { const items = requests.filter((request) => laneFor(request) === lane.id); return { ...lane, total: items.length, complete: items.filter(isCompleted).length, attention: items.filter((request) => isOverdue(request) || isDueSoon(request)).length }; }), [requests]);
  const attentionQueue = useMemo(() => [...requests].filter((request) => !isCompleted(request) && (request.sampleRequiredDate || request.status)).sort((a, b) => Number(isOverdue(b)) - Number(isOverdue(a)) || String(a.sampleRequiredDate || "9999").localeCompare(String(b.sampleRequiredDate || "9999"))).slice(0, 8), [requests]);
  const recentRequests = useMemo(() => [...requests].sort((a, b) => String(b.dateRequestCreated || b.createdAt).localeCompare(String(a.dateRequestCreated || a.createdAt))).slice(0, 8), [requests]);
  const completedQueue = useMemo(() => requests.filter(isCompleted).slice(0, 8), [requests]);
  const visibleQueue = useMemo(() => { const source = queueView === "attention" ? attentionQueue : queueView === "completed" ? completedQueue : recentRequests; const query = search.trim().toLowerCase(); return query ? source.filter((request) => [request.srNumber, request.productDescription, request.customer, request.status].some((value) => String(value || "").toLowerCase().includes(query))) : source; }, [attentionQueue, completedQueue, recentRequests, queueView, search]);
  const demandRows = useMemo(() => { const map = new Map<string, number>(); requests.forEach((request) => { const name = request.customer?.trim() || "Unassigned"; map.set(name, (map.get(name) || 0) + 1); }); const rows = [...map.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5); const max = Math.max(...rows.map(([, count]) => count), 1); return rows.map(([name, count]) => ({ name, count, width: Math.round((count / max) * 100) })); }, [requests]);

  const openSpecs = async (request: SampleRequestItem) => { setSelectedRequest(request); setIsLoadingSpecs(true); try { setSpecDetails(await fetchProductDetailsApi(request.id)); } catch { setSpecDetails([]); } finally { setIsLoadingSpecs(false); } };
  const firstName = user?.name?.split(" ")[0] || "Admin";
  const currentDate = new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" });

  return <div className="erp-dashboard">
    <header className="erp-dashboard-header"><div><div className="erp-context-line"><span className="erp-live-dot" /> SAMP Operations <span>/</span> All workstreams</div><h1>Good {new Date().getHours() < 12 ? "morning" : new Date().getHours() < 17 ? "afternoon" : "evening"}, {firstName}</h1><p>One operating view for intake, design, production readiness, and dispatch.</p></div><div className="erp-header-actions"><span className="erp-date-label">{currentDate}</span><button type="button" className="erp-button erp-button-secondary" onClick={() => loadDashboardData(true)} disabled={isRefreshing}><RefreshCw size={15} className={isRefreshing ? "animate-spin" : ""} /> Refresh</button><button type="button" className="erp-button erp-button-primary" onClick={() => navigate("/sample-requests/new")}><Plus size={15} /> New request</button></div></header>

    <section className="erp-kpi-grid" aria-label="Operations summary">{[
      { label: "Open requests", value: metrics.open, detail: `${metrics.total} total in system`, icon: Layers, tone: "blue", action: () => navigate("/sample-requests") },
      { label: "Needs attention", value: metrics.overdue + metrics.dueSoon, detail: `${metrics.overdue} overdue · ${metrics.dueSoon} due soon`, icon: AlertCircle, tone: "orange", action: () => setQueueView("attention") },
      { label: "Completed", value: metrics.completed, detail: `${metrics.completionRate}% of current volume`, icon: CheckCircle2, tone: "green", action: () => setQueueView("completed") },
      { label: "Commercial pipeline", value: metrics.costing, detail: `${metrics.customers} customers · ${metrics.plants} plants`, icon: BarChart3, tone: "violet", action: () => navigate("/costing-team") },
    ].map((metric) => { const Icon = metric.icon; return <button key={metric.label} type="button" className={`erp-kpi-card tone-${metric.tone}`} onClick={metric.action}><div className="erp-kpi-top"><span className="erp-kpi-label">{metric.label}</span><Icon size={17} /></div><strong>{isLoading ? "—" : metric.value.toLocaleString()}</strong><span className="erp-kpi-detail">{metric.detail}</span></button>; })}</section>

    <div className="erp-main-grid"><section className="erp-panel erp-queue-panel"><div className="erp-panel-header"><div><div className="erp-panel-kicker">Work center</div><h2>Request queue</h2><p>Review, filter, and open the work that moves the pipeline.</p></div><button type="button" className="erp-link-button" onClick={() => navigate("/sample-requests")}>Open full queue <ArrowRight size={14} /></button></div><div className="erp-queue-toolbar"><div className="erp-tabs" role="tablist" aria-label="Request queue views">{(["attention", "all", "completed"] as QueueView[]).map((view) => <button key={view} type="button" role="tab" aria-selected={queueView === view} className={queueView === view ? "active" : ""} onClick={() => setQueueView(view)}>{view === "attention" ? "Needs attention" : view === "all" ? "Recently updated" : "Completed"}</button>)}</div><label className="erp-search"><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search requests" aria-label="Search requests" /></label></div><div className="erp-table-wrap"><table className="erp-table"><thead><tr><th>Request</th><th>Customer / owner</th><th>Stage</th><th>Target</th><th aria-label="Open" /></tr></thead><tbody>{visibleQueue.map((request) => { const tone = statusTone(request); return <tr key={request.id}><td><button type="button" className="erp-request-cell" onClick={() => openSpecs(request)}><span>{request.srNumber || `REQ-${request.id}`}</span><strong>{request.productDescription || "Untitled request"}</strong></button></td><td><span className="erp-primary-cell">{request.customer || "Unassigned"}</span><span className="erp-secondary-cell">{request.createdBy || "Admin"}</span></td><td><span className={`erp-status ${tone.className}`}><span />{tone.label}</span></td><td><span className="erp-date-cell">{formatDate(request.sampleRequiredDate)}</span></td><td><button type="button" className="erp-row-action" onClick={() => openSpecs(request)} aria-label={`Open ${request.srNumber || "request"}`}><ChevronRight size={16} /></button></td></tr>; })}</tbody></table>{isLoading && <div className="erp-empty-state">Loading operational data…</div>}{!isLoading && visibleQueue.length === 0 && <div className="erp-empty-state">No requests match this view.</div>}</div></section>

      <aside className="erp-side-stack"><section className="erp-panel erp-attention-panel"><div className="erp-panel-header compact"><div><div className="erp-panel-kicker">Exceptions</div><h2>What needs action</h2></div><span className="erp-count-badge">{metrics.overdue + metrics.dueSoon}</span></div><div className="erp-exception-list">{attentionQueue.slice(0, 4).map((request) => <button type="button" className="erp-exception-row" key={request.id} onClick={() => openSpecs(request)}><span className={`erp-exception-icon ${isOverdue(request) ? "danger" : "warning"}`}><Clock size={14} /></span><span><strong>{request.srNumber || "Request"}</strong><small>{request.productDescription || "Untitled request"}</small></span><span className="erp-exception-date">{isOverdue(request) ? "Overdue" : "Due soon"}<small>{formatDate(request.sampleRequiredDate)}</small></span></button>)}{!isLoading && attentionQueue.length === 0 && <div className="erp-empty-state small">No active exceptions.</div>}</div><button type="button" className="erp-panel-footer" onClick={() => navigate("/notifications")}>View notifications <ArrowRight size={14} /></button></section><section className="erp-panel erp-actions-panel"><div className="erp-panel-header compact"><div><div className="erp-panel-kicker">Shortcuts</div><h2>Quick actions</h2></div><Settings size={16} /></div><div className="erp-quick-actions"><button type="button" onClick={() => navigate("/sample-requests/new")}><Plus size={16} /><span><strong>Create request</strong><small>Start a new sample brief</small></span><ChevronRight size={15} /></button><button type="button" onClick={() => setIsPlantModalOpen(true)}><Factory size={16} /><span><strong>Manage plants</strong><small>Routing and capacity</small></span><ChevronRight size={15} /></button><button type="button" onClick={() => navigate("/members")}><Users size={16} /><span><strong>Team directory</strong><small>{users.length} accounts</small></span><ChevronRight size={15} /></button></div></section></aside></div>

    <section className="erp-panel erp-pipeline-panel"><div className="erp-panel-header"><div><div className="erp-panel-kicker">Process visibility</div><h2>Pipeline by workstream</h2><p>Where requests are sitting across the operating model.</p></div><button type="button" className="erp-link-button" onClick={() => navigate("/sample-requests")}>View all stages <ArrowRight size={14} /></button></div><div className="erp-pipeline-track">{laneStats.map((lane, index) => <React.Fragment key={lane.id}><button type="button" className="erp-stage" onClick={() => navigate("/sample-requests", { state: { initialFilterTab: lane.id === "marketing" ? "draft" : lane.id } })}><span className="erp-stage-index">0{index + 1}</span><span className="erp-stage-icon" style={{ backgroundColor: lane.soft, color: lane.color }}>{lane.id === "marketing" ? <FileText size={16} /> : lane.id === "creative" ? <Layers size={16} /> : lane.id === "studio" ? <Building2 size={16} /> : <Factory size={16} />}</span><strong>{lane.label}</strong><small>{lane.description}</small><div className="erp-stage-stats"><b>{isLoading ? "—" : lane.total}</b><span>requests</span><em>{lane.attention ? `${lane.attention} due` : "On track"}</em></div><div className="erp-stage-bar"><span style={{ width: `${lane.total ? Math.max(Math.round((lane.complete / lane.total) * 100), 7) : 0}%`, background: lane.color }} /></div></button>{index < laneStats.length - 1 && <ArrowRight className="erp-stage-arrow" size={17} />}</React.Fragment>)}</div></section>

    <div className="erp-bottom-grid"><section className="erp-panel"><div className="erp-panel-header compact"><div><div className="erp-panel-kicker">Portfolio</div><h2>Demand concentration</h2></div><span className="erp-panel-meta">Top customers</span></div><div className="erp-demand-list">{demandRows.map((row, index) => <div className="erp-demand-row" key={row.name}><div><span className="erp-rank">{index + 1}</span><strong>{row.name}</strong><b>{row.count}</b></div><span className="erp-demand-bar"><i style={{ width: `${row.width}%` }} /></span></div>)}{demandRows.length === 0 && <div className="erp-empty-state small">No demand data available.</div>}</div><div className="erp-mini-summary"><span><small>Customers</small><b>{metrics.customers}</b></span><span><small>Plants</small><b>{metrics.plants}</b></span><span><small>Live volume</small><b>{metrics.total}</b></span></div></section><section className="erp-panel"><div className="erp-panel-header compact"><div><div className="erp-panel-kicker">Capacity</div><h2>Team readiness</h2></div><button type="button" className="erp-link-button" onClick={() => navigate("/members")}>Directory <ArrowRight size={14} /></button></div><div className="erp-readiness-grid"><div><span className="erp-readiness-icon green"><Users size={15} /></span><strong>{users.filter((member) => member.is_active).length}</strong><small>Active staff</small></div><div><span className="erp-readiness-icon violet"><CheckCircle2 size={15} /></span><strong>{users.filter((member) => (member.role || "").toLowerCase().includes("admin") || (member.sub_role || "").toLowerCase().includes("lead")).length}</strong><small>Review leads</small></div><div><span className="erp-readiness-icon orange"><Factory size={15} /></span><strong>{metrics.plants}</strong><small>Plants in use</small></div><div><span className="erp-readiness-icon blue"><Workflow size={15} /></span><strong>Live</strong><small>Refresh status</small></div></div><div className="erp-team-strip"><div className="erp-avatar-stack">{users.slice(0, 7).map((member) => <span key={member.id} title={member.name}>{initials(member.name)}</span>)}{users.length > 7 && <span>+{users.length - 7}</span>}</div><button type="button" className="erp-text-button" onClick={() => loadDashboardData(true)} disabled={isRefreshing}><RefreshCw size={13} /> Refresh control room</button></div></section></div>

    {selectedRequest && <ProductSpecificationsDrawer product={selectedRequest} details={specDetails} isLoading={isLoadingSpecs} specMode="view" allowEdit={false} onClose={() => { setSelectedRequest(null); setSpecDetails([]); }} />}<PlantManagementModal isOpen={isPlantModalOpen} onClose={() => setIsPlantModalOpen(false)} currentUser={user} />
  </div>;
};

export default DashboardOverview;
